package com.bkap.vn.common.entity;

import org.hibernate.validator.constraints.NotBlank;

import java.util.Date;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Accessories generated by hbm2java
 */
@Entity
@Table(name="accessories"
        ,schema="dbo"
        ,catalog="shop_online"
)
public class Accessories  implements java.io.Serializable {


    private int id;
    private String name;
    private String detail;
    private Integer adminCreate;
    private Integer adminUpdate;
    private Date createDate;
    private Date updateDate;

    public Accessories() {
    }


    public Accessories(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Accessories(int id, String name, String detail, Integer adminCreate, Integer adminUpdate, Date createDate, Date updateDate) {
        this.id = id;
        this.name = name;
        this.detail = detail;
        this.adminCreate = adminCreate;
        this.adminUpdate = adminUpdate;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name="detail")
    public String getDetail() {
        return this.detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }


    @Column(name="admin_create")
    public Integer getAdminCreate() {
        return this.adminCreate;
    }

    public void setAdminCreate(Integer adminCreate) {
        this.adminCreate = adminCreate;
    }


    @Column(name="admin_update")
    public Integer getAdminUpdate() {
        return this.adminUpdate;
    }

    public void setAdminUpdate(Integer adminUpdate) {
        this.adminUpdate = adminUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}