package com.bkap.vn.common.entity;
// Generated Aug 12, 2017 10:45:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.*;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin"
        , schema = "dbo"
        , catalog = "shop_online"
)
public class Admin implements java.io.Serializable {


    private int id;
    private String account;
    private String password;
    private String email;
    private String phone;
    private Date birthday;
    private String address;
    private Integer adminCreate;
    private Integer adminUpdate;
    private Date createDate;
    private Date updateDate;
    private byte activeStatus;
    private byte status;
     /*private Set<RoleByGroupRole> roleByGroupRolesForAdminCreate = new HashSet<RoleByGroupRole>(0);
     private Set<OrderDetail> orderDetailsForAdminCreate = new HashSet<OrderDetail>(0);
     private Set<Product> productsForAdminCreate = new HashSet<Product>(0);
     private Set<Role> rolesForAdminCreate = new HashSet<Role>(0);
     private Set<User> usersForAdminUpdate = new HashSet<User>(0);
     private Set<RoleByGroupRole> roleByGroupRolesForAdminUpdate = new HashSet<RoleByGroupRole>(0);
     private Set<Order> ordersForAdminUpdate = new HashSet<Order>(0);
     private Set<GroupRole> groupRolesForAdminUpdate = new HashSet<GroupRole>(0);
     private Set<News> newsesForAdminCreate = new HashSet<News>(0);
     private Set<HistoryAction> historyActions = new HashSet<HistoryAction>(0);
     private Set<ProductGift> productGiftsForAdminCreate = new HashSet<ProductGift>(0);
     private Set<User> usersForAdminCreate = new HashSet<User>(0);
     private Set<Product> productsForAdminUpdate = new HashSet<Product>(0);
     private Set<OrderDetail> orderDetailsForAdminUpdate = new HashSet<OrderDetail>(0);
     private Set<ProductGift> productGiftsForAdminUpdate = new HashSet<ProductGift>(0);
     private Set<Category> categoriesForAdminUpdate = new HashSet<Category>(0);
     private Set<Province> provincesForAdminUpdate = new HashSet<Province>(0);
     private Set<News> newsesForAdminUpdate = new HashSet<News>(0);
     private Set<Transaction> transactionsForAdminCreate = new HashSet<Transaction>(0);
     private Set<Transaction> transactionsForAdminUpdate = new HashSet<Transaction>(0);
     private Set<Order> ordersForAdminCreate = new HashSet<Order>(0);
     private Set<Gift> giftsForAdminCreate = new HashSet<Gift>(0);
     private Set<Role> rolesForAdminUpdate = new HashSet<Role>(0);
     private Set<Gift> giftsForAdminUpdate = new HashSet<Gift>(0);
     private Set<Category> categoriesForAdminCreate = new HashSet<Category>(0);
     private Set<Province> provincesForAdminCreate = new HashSet<Province>(0);
     private Set<GroupRole> groupRolesForAdminCreate = new HashSet<GroupRole>(0);*/

    public Admin() {
    }

    public Admin(int id, String account, String password, String email, byte activeStatus, byte status) {
        this.id = id;
        this.account = account;
        this.password = password;
        this.email = email;
        this.activeStatus = activeStatus;
        this.status = status;
    }

    public Admin(int id, String account, String password, String email, String phone, Date birthday, String address, Integer adminCreate, Integer adminUpdate, Date createDate, Date updateDate, byte activeStatus, byte status) {
        this.id = id;
        this.account = account;
        this.password = password;
        this.email = email;
        this.phone = phone;
        this.birthday = birthday;
        this.address = address;
        this.adminCreate = adminCreate;
        this.adminUpdate = adminUpdate;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.activeStatus = activeStatus;
        this.status = status;

    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "account", nullable = false)
    public String getAccount() {
        return this.account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    @Column(name = "password", nullable = false)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "email", nullable = false)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "phone")
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "birthday", length = 23)
    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    @Column(name = "address")
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "admin_create")
    public Integer getAdminCreate() {
        return this.adminCreate;
    }

    public void setAdminCreate(Integer adminCreate) {
        this.adminCreate = adminCreate;
    }


    @Column(name = "admin_update")
    public Integer getAdminUpdate() {
        return this.adminUpdate;
    }

    public void setAdminUpdate(Integer adminUpdate) {
        this.adminUpdate = adminUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Column(name = "active_status", nullable = false)
    public byte getActiveStatus() {
        return this.activeStatus;
    }

    public void setActiveStatus(byte activeStatus) {
        this.activeStatus = activeStatus;
    }

    @Column(name = "status", nullable = false)
    public byte getStatus() {
        return this.status;
    }

    public void setStatus(byte status) {
        this.status = status;
    }
}


