package com.bkap.vn.common.entity;
// Generated Dec 31, 2017 11:05:57 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

/**
 * AdminRole generated by hbm2java
 */
@Entity
@Table(name = "admin_role"
        , schema = "dbo"
        , catalog = "shop_online"
)
public class AdminRole implements java.io.Serializable {
    private int id;
    private Admin admin;
    private Role role;

    public AdminRole() {
    }

    public AdminRole(Admin admin, Role role) {
        this.admin = admin;
        this.role = role;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "admin_id", nullable = false)
    public Admin getAdmin() {
        return this.admin;
    }

    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "role_id", nullable = false)
    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }


}


