package com.bkap.vn.common.entity;
// Generated Dec 6, 2017 9:49:55 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Gift generated by hbm2java
 */
@Entity
@Table(name="gift"
    ,schema="dbo"
    ,catalog="shop_online"
)
public class Gift  implements java.io.Serializable {


     private int id;
     private Admin adminByAdminCreate;
     private Admin adminByAdminUpdate;
     private String name;
     private String description;
     private Date createDate;
     private Date updateDate;
     private Set<ProductGift> productGifts = new HashSet<ProductGift>(0);

    public Gift() {
    }

	
    public Gift(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Gift(int id, Admin adminByAdminCreate, Admin adminByAdminUpdate, String name, String description, Date createDate, Date updateDate, Set<ProductGift> productGifts) {
       this.id = id;
       this.adminByAdminCreate = adminByAdminCreate;
       this.adminByAdminUpdate = adminByAdminUpdate;
       this.name = name;
       this.description = description;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.productGifts = productGifts;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_create")
    public Admin getAdminByAdminCreate() {
        return this.adminByAdminCreate;
    }
    
    public void setAdminByAdminCreate(Admin adminByAdminCreate) {
        this.adminByAdminCreate = adminByAdminCreate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_update")
    public Admin getAdminByAdminUpdate() {
        return this.adminByAdminUpdate;
    }
    
    public void setAdminByAdminUpdate(Admin adminByAdminUpdate) {
        this.adminByAdminUpdate = adminByAdminUpdate;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="create_date", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="update_date", length=23)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gift")
    public Set<ProductGift> getProductGifts() {
        return this.productGifts;
    }
    
    public void setProductGifts(Set<ProductGift> productGifts) {
        this.productGifts = productGifts;
    }




}


