package com.bkap.vn.common.entity;
// Generated Dec 6, 2017 9:49:55 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoryAction generated by hbm2java
 */
@Entity
@Table(name="history_action"
    ,schema="dbo"
    ,catalog="shop_online"
)
public class HistoryAction  implements java.io.Serializable {


     private int id;
     private Admin admin;
     private String clientInfo;
     private String accessType;
     private Date executeDate;
     private String description;

    public HistoryAction() {
    }

    public HistoryAction(int id, Admin admin, String clientInfo, String accessType, Date executeDate, String description) {
       this.id = id;
       this.admin = admin;
       this.clientInfo = clientInfo;
       this.accessType = accessType;
       this.executeDate = executeDate;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_id", nullable=false)
    public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }

    
    @Column(name="client_info", nullable=false)
    public String getClientInfo() {
        return this.clientInfo;
    }
    
    public void setClientInfo(String clientInfo) {
        this.clientInfo = clientInfo;
    }

    
    @Column(name="access_type", nullable=false)
    public String getAccessType() {
        return this.accessType;
    }
    
    public void setAccessType(String accessType) {
        this.accessType = accessType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="execute_date", nullable=false, length=23)
    public Date getExecuteDate() {
        return this.executeDate;
    }
    
    public void setExecuteDate(Date executeDate) {
        this.executeDate = executeDate;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


