package com.bkap.vn.common.entity;
// Generated Dec 31, 2017 11:05:57 PM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Date;

/**
 * PersistentLogins generated by hbm2java
 */
@Entity
@Table(name="persistent_logins"
    ,schema="dbo"
    ,catalog="shop_online"
)
public class PersistentLogins{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private String id;
    @Column(name = "account", nullable = false)
    private String username;
    @Column(name = "series", nullable = false)
    private String series;
    @Column(name = "token", nullable = false)
    private String token;
    @Column(name = "last_used", nullable = false)
    private Date lastUsed;

    public PersistentLogins() {
    }


    public PersistentLogins(String id, String username, String series, String token, Date lastUsed) {
        this.id = id;
        this.username = username;
        this.series = series;
        this.token = token;
        this.lastUsed = lastUsed;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getSeries() {
        return series;
    }

    public void setSeries(String series) {
        this.series = series;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Date getLastUsed() {
        return lastUsed;
    }

    public void setLastUsed(Date lastUsed) {
        this.lastUsed = lastUsed;
    }
}


