package com.bkap.vn.common.entity;
// Generated Aug 12, 2017 10:45:55 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,schema="dbo"
    ,catalog="shop_online"
)
public class Product  implements Serializable {


     private int id;
     private Admin adminByAdminCreate;
     private Admin adminByAdminUpdate;
     private Category category;
     private Serializable productName;
     private double price;
     private double discount;
     private Serializable imageLink;
     private Serializable imageList;
     private Double countView;
     private Date createDate;
     private Date updateDate;
     private Serializable detail;
     private byte status;
     private Set<ProductGift> productGifts = new HashSet<ProductGift>(0);

    public Product() {
    }

	
    public Product(int id, Category category, Serializable productName, double price, double discount, byte status) {
        this.id = id;
        this.category = category;
        this.productName = productName;
        this.price = price;
        this.discount = discount;
        this.status = status;
    }
    public Product(int id, Admin adminByAdminCreate, Admin adminByAdminUpdate, Category category, Serializable productName, double price, double discount, Serializable imageLink, Serializable imageList, Double countView, Date createDate, Date updateDate, Serializable detail, byte status, Set<ProductGift> productGifts) {
       this.id = id;
       this.adminByAdminCreate = adminByAdminCreate;
       this.adminByAdminUpdate = adminByAdminUpdate;
       this.category = category;
       this.productName = productName;
       this.price = price;
       this.discount = discount;
       this.imageLink = imageLink;
       this.imageList = imageList;
       this.countView = countView;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.detail = detail;
       this.status = status;
       this.productGifts = productGifts;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_create")
    public Admin getAdminByAdminCreate() {
        return this.adminByAdminCreate;
    }
    
    public void setAdminByAdminCreate(Admin adminByAdminCreate) {
        this.adminByAdminCreate = adminByAdminCreate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_update")
    public Admin getAdminByAdminUpdate() {
        return this.adminByAdminUpdate;
    }
    
    public void setAdminByAdminUpdate(Admin adminByAdminUpdate) {
        this.adminByAdminUpdate = adminByAdminUpdate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="product_name", nullable=false)
    public Serializable getProductName() {
        return this.productName;
    }
    
    public void setProductName(Serializable productName) {
        this.productName = productName;
    }

    
    @Column(name="price", nullable=false, precision=53, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="discount", nullable=false, precision=53, scale=0)
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }

    
    @Column(name="image_link")
    public Serializable getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(Serializable imageLink) {
        this.imageLink = imageLink;
    }

    
    @Column(name="image_list")
    public Serializable getImageList() {
        return this.imageList;
    }
    
    public void setImageList(Serializable imageList) {
        this.imageList = imageList;
    }

    
    @Column(name="count_view", precision=53, scale=0)
    public Double getCountView() {
        return this.countView;
    }
    
    public void setCountView(Double countView) {
        this.countView = countView;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=23)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="detail")
    public Serializable getDetail() {
        return this.detail;
    }
    
    public void setDetail(Serializable detail) {
        this.detail = detail;
    }

    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<ProductGift> getProductGifts() {
        return this.productGifts;
    }
    
    public void setProductGifts(Set<ProductGift> productGifts) {
        this.productGifts = productGifts;
    }




}


