package com.bkap.vn.common.entity;
// Generated Dec 6, 2017 9:49:55 PM by Hibernate Tools 4.3.1


import org.hibernate.validator.constraints.NotBlank;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role"
        , schema = "dbo"
        , catalog = "shop_online"
)
public class Role implements java.io.Serializable {


    private int id;
    private String roleName;
    private String type;
    public Role() {
    }


    public Role(int id, String roleName) {
        this.id = id;
        this.roleName = roleName;
    }

    public Role(int id, String roleName,String type) {
        this.id = id;
        this.roleName = roleName;
        this.type = type;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "role_name", nullable = false)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "type", length = 23)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}


