package com.bkap.vn.common.entity;
// Generated Dec 6, 2017 9:49:55 PM by Hibernate Tools 4.3.1


import org.hibernate.validator.constraints.NotBlank;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role"
        , schema = "dbo"
        , catalog = "shop_online"
)
public class Role implements java.io.Serializable {


    private int id;
    private Admin adminByAdminCreate;
    private Admin adminByAdminUpdate;
    @NotNull(message = "Tên quyền không được để trống!")
    @NotBlank(message = "Tên quyền không được để trống!")
    @Size(max = 100, message = "Tên quyền không được dài quá 100 kí tự!")
    private String roleName;
    @Size(max = 500, message = "Nội dung không được dài quá 500 kí tự!")
    private String description;
    private Date createDate;
    private Date updateDate;
    private Set<RoleByGroupRole> roleByGroupRoles = new HashSet<RoleByGroupRole>(0);

    public Role() {
    }


    public Role(int id, String roleName) {
        this.id = id;
        this.roleName = roleName;
    }

    public Role(int id, Admin adminByAdminCreate, Admin adminByAdminUpdate, String roleName, String description, Date createDate, Date updateDate, Set<RoleByGroupRole> roleByGroupRoles) {
        this.id = id;
        this.adminByAdminCreate = adminByAdminCreate;
        this.adminByAdminUpdate = adminByAdminUpdate;
        this.roleName = roleName;
        this.description = description;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.roleByGroupRoles = roleByGroupRoles;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admin_create")
    public Admin getAdminByAdminCreate() {
        return this.adminByAdminCreate;
    }

    public void setAdminByAdminCreate(Admin adminByAdminCreate) {
        this.adminByAdminCreate = adminByAdminCreate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admin_update")
    public Admin getAdminByAdminUpdate() {
        return this.adminByAdminUpdate;
    }

    public void setAdminByAdminUpdate(Admin adminByAdminUpdate) {
        this.adminByAdminUpdate = adminByAdminUpdate;
    }


    @Column(name = "role_name", nullable = false)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }


    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "create_date", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "update_date", length = 23)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    public Set<RoleByGroupRole> getRoleByGroupRoles() {
        return this.roleByGroupRoles;
    }

    public void setRoleByGroupRoles(Set<RoleByGroupRole> roleByGroupRoles) {
        this.roleByGroupRoles = roleByGroupRoles;
    }


}


