package com.bkap.vn.common.entity;
// Generated Dec 6, 2017 9:49:55 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name="transaction"
    ,schema="dbo"
    ,catalog="shop_online"
)
public class Transaction  implements java.io.Serializable {


     private int id;
     private Admin adminByAdminCreate;
     private Admin adminByAdminUpdate;
     private int userId;
     private String userName;
     private String userEmail;
     private String userPhone;
     private double amount;
     private String payment;
     private String paymentInfo;
     private String message;
     private String security;
     private Date createDate;
     private Date updateDate;

    public Transaction() {
    }

	
    public Transaction(int id, int userId, String userName, String userEmail, String userPhone, double amount, String payment) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.userEmail = userEmail;
        this.userPhone = userPhone;
        this.amount = amount;
        this.payment = payment;
    }
    public Transaction(int id, Admin adminByAdminCreate, Admin adminByAdminUpdate, int userId, String userName, String userEmail, String userPhone, double amount, String payment, String paymentInfo, String message, String security, Date createDate, Date updateDate) {
       this.id = id;
       this.adminByAdminCreate = adminByAdminCreate;
       this.adminByAdminUpdate = adminByAdminUpdate;
       this.userId = userId;
       this.userName = userName;
       this.userEmail = userEmail;
       this.userPhone = userPhone;
       this.amount = amount;
       this.payment = payment;
       this.paymentInfo = paymentInfo;
       this.message = message;
       this.security = security;
       this.createDate = createDate;
       this.updateDate = updateDate;
    }
   
     @Id

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_create")
    public Admin getAdminByAdminCreate() {
        return this.adminByAdminCreate;
    }
    
    public void setAdminByAdminCreate(Admin adminByAdminCreate) {
        this.adminByAdminCreate = adminByAdminCreate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin_update")
    public Admin getAdminByAdminUpdate() {
        return this.adminByAdminUpdate;
    }
    
    public void setAdminByAdminUpdate(Admin adminByAdminUpdate) {
        this.adminByAdminUpdate = adminByAdminUpdate;
    }

    
    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="user_name", nullable=false)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_email", nullable=false)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="user_phone", nullable=false)
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    
    @Column(name="amount", nullable=false, precision=53, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="payment", nullable=false)
    public String getPayment() {
        return this.payment;
    }
    
    public void setPayment(String payment) {
        this.payment = payment;
    }

    
    @Column(name="payment_info")
    public String getPaymentInfo() {
        return this.paymentInfo;
    }
    
    public void setPaymentInfo(String paymentInfo) {
        this.paymentInfo = paymentInfo;
    }

    
    @Column(name="message")
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="security")
    public String getSecurity() {
        return this.security;
    }
    
    public void setSecurity(String security) {
        this.security = security;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="create_date", length=23)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="update_date", length=23)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


